# 高性能文件上传客户端配置文件
# 格式: TOML (Tom's Obvious, Minimal Language) v1.0.0
# 编码: UTF-8
# 生成时间: 2025-09-30
#
# 配置说明:
# - 使用 # 开头的行为注释
# - 字符串值使用双引号包围
# - 布尔值使用 true/false
# - 整数直接写数字
# - 数组使用方括号 [item1, item2]

# =============================================================================
# 上传配置 - 控制文件上传的核心参数
# =============================================================================
[upload]

# 服务器连接设置
server_host = "localhost"           # 上传服务器地址
server_port = 8080                  # 服务器端口号
upload_protocol = "HTTP"            # 上传协议: HTTP, HTTPS, FTP

# 并发和性能配置
max_concurrent_uploads = 4          # 最大并发上传数 (1-16)
chunk_size = 1048576               # 分块大小 (字节), 1MB = 1048576
timeout_seconds = 30               # 超时时间 (秒)
max_upload_speed = 0               # 最大上传速度限制 (0=无限制, 单位: bytes/s)
max_file_size = 0                  # 最大文件大小限制 (0=无限制, 单位: bytes)

# 重试策略
retry_count = 3                    # 失败重试次数
retry_delay_ms = 1000              # 重试延迟 (毫秒)

# 功能开关
enable_resume = true               # 启用断点续传
enable_compression = false         # 启用压缩 (可选: gzip, deflate, lz4)
compression_algorithm = "gzip"     # 压缩算法: none, gzip, deflate, lz4, brotli
enable_checksum = true             # 启用文件校验
checksum_algorithm = "md5"         # 校验算法: none, md5, sha1, sha256, crc32
overwrite = false                  # 覆盖现有文件
enable_multipart = true            # 启用分块上传
enable_progress = true             # 启用进度报告

# 目标和路径配置
target_dir = "/uploads"            # 服务器目标目录
exclude_patterns = [               # 排除文件模式
    "*.tmp",
    "*.log",
    ".*",                          # 隐藏文件
    "node_modules/",
    "__pycache__/"
]

# SSL/TLS 安全配置
use_ssl = false                    # 使用SSL加密
cert_file = ""                     # 客户端证书文件路径
private_key_file = ""              # 私钥文件路径
ca_file = ""                       # CA证书文件路径
verify_server = true               # 验证服务器证书

# 认证配置
auth_token = ""                    # API认证令牌

# 日志配置
log_level = "INFO"                 # 日志级别: DEBUG, INFO, WARNING, ERROR
log_file_path = "logs/client.log"  # 日志文件路径
enable_detailed_log = false        # 启用详细日志

# 客户端信息
client_version = "1.0.0"           # 客户端版本号
user_agent = "HighPerformanceUploadClient/1.0.0"  # 用户代理字符串

# =============================================================================
# 用户界面配置 - 控制客户端界面显示和行为
# =============================================================================
[ui]

# 进度显示配置
show_progress_details = true       # 显示详细进度信息
show_speed_info = true             # 显示上传速度
show_file_size = true              # 显示文件大小
show_file_type = true              # 显示文件类型
show_upload_time = true            # 显示上传时间
show_file_status = true            # 显示文件状态

# 界面行为
auto_start_upload = false          # 自动开始上传
minimize_to_tray = true            # 最小化到系统托盘
show_notifications = true          # 显示系统通知

# 本地化和主题
language = "zh_CN"                 # 界面语言: en_US, zh_CN, ja_JP
theme = "default"                  # 界面主题: default, dark, light

# 窗口设置
window_width = 800                 # 窗口宽度 (像素)
window_height = 600                # 窗口高度 (像素)
window_maximized = false           # 窗口最大化状态

# =============================================================================
# 网络配置 - 控制网络连接和通信参数
# =============================================================================
[network]

# 超时配置 (毫秒)
connect_timeout_ms = 5000          # 连接超时
read_timeout_ms = 30000            # 读取超时
write_timeout_ms = 30000           # 写入超时

# 缓冲和连接配置
buffer_size = 8192                 # 缓冲区大小 (字节)
max_connections = 10               # 最大连接数

# 保活配置
enable_keep_alive = true           # 启用TCP Keep-Alive
keep_alive_interval_ms = 30000     # Keep-Alive间隔 (毫秒)

# 代理配置
enable_proxy = false               # 启用代理
proxy_host = ""                    # 代理服务器地址
proxy_port = 8080                  # 代理端口
proxy_user = ""                    # 代理用户名
proxy_password = ""                # 代理密码

# =============================================================================
# 高级配置 - 专家级用户配置选项
# =============================================================================
[advanced]

# 内存管理
max_memory_usage_mb = 512          # 最大内存使用 (MB)
enable_memory_pool = true          # 启用内存池

# 线程配置
worker_threads = 0                 # 工作线程数 (0=自动检测CPU核心数)
io_threads = 2                     # I/O线程数

# 缓存配置
enable_file_cache = true           # 启用文件缓存
cache_size_mb = 100               # 缓存大小 (MB)
cache_duration_hours = 24          # 缓存持续时间 (小时)

# 性能调优
enable_tcp_nodelay = true          # 启用TCP_NODELAY
tcp_send_buffer_size = 65536       # TCP发送缓冲区大小
tcp_recv_buffer_size = 65536       # TCP接收缓冲区大小

# 调试和监控
enable_performance_metrics = false  # 启用性能指标收集
metrics_interval_seconds = 60       # 指标收集间隔 (秒)
enable_debug_mode = false          # 启用调试模式

# =============================================================================
# 配置文件元信息
# =============================================================================
[meta]
config_version = "1.0.0"          # 配置文件版本
created_by = "ClientConfigManager" # 创建者
last_modified = "2025-09-30T10:00:00Z"  # 最后修改时间 (ISO 8601格式)