# ==========================================
# LocalUploadServer 配置文件
# ==========================================

# ==========================================
# 网络配置
# ==========================================
[network]
# 服务器监听地址
host = "127.0.0.1"

# 服务器监听端口
port = 9000

# 接收缓冲区大小（字节）
buffer_size = 8192

# 重连间隔（毫秒）
reconnect_interval_ms = 1000

# ==========================================
# 心跳检测配置
# ==========================================
[heartbeat]
# 是否启用心跳检测（服务器端）
enable_heartbeat_check = true

# 客户端心跳超时时间（毫秒）
# 如果客户端超过此时间未发送心跳，将被断开连接
# 建议设置为客户端心跳间隔的 3-6 倍
heartbeat_timeout_ms = 60000

# 心跳检查间隔（毫秒）
# 服务器每隔此时间检查一次所有客户端的心跳状态
heartbeat_check_interval_ms = 5000

# ==========================================
# 日志配置
# ==========================================
[logging]
# 日志级别：DEBUG, INFO, WARN, ERROR
log_level = "INFO"

# 是否启用心跳日志（DEBUG 级别）
enable_heartbeat_log = true

# 日志文件路径
log_directory = "logs"

# ==========================================
# 性能配置
# ==========================================
[performance]
# 最大客户端连接数
max_clients = 100

# 是否启用 TCP Keep-Alive
enable_tcp_keepalive = true

# TCP Keep-Alive 间隔（毫秒）
tcp_keepalive_interval_ms = 30000
